name: Publish to Pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.11
      - run: |
          python3 -m pip install -U pip pipenv
          python3 -m pipenv install
          python3 -m pipenv install --system --dev
          sphinx-build -b html docs pages
      - name: Build and deploy Sphinx site
        uses: sphinx-contrib/makedomain@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
